#!/usr/bin/env python3
"""P7 criterion i-b (synthetic half): three ways of taking the same within-batch constant — where exactly they differ, and when they start to differ at all.

`P7_DECISION.md` criterion i-b. **Zero GPU.**

--- First, get the relationships straight (this section overturns the loose phrase "three estimators") ---

TB residual:  Δ_i = C + (1/|y_i|)·log(π/π_ref) − β·r_i

  GFlowRL (Eq. 4)  C = mean_i[ β·r_i + log π_ref − log π_old ], uses **π_old**, and **sg[]**
  VarGrad          C* = the constant minimizing Σ Δ_i², uses **π_θ**, and **carries gradient**
  DevGrad (f-TB)   C* = the constant minimizing (1/B) Σ L_f(Δ_i + C), **no longer the mean when f is not square**

**So: with square loss + π_θ = π_old, all three are numerically identical.** They differ in only two places:
  (a) whether gradient flows through the constant (GFlowRL's sg[] vs VarGrad) — only shows up once π_θ drifts away within a minibatch;
  (b) the choice of f (square -> mean; absolute value -> median; Huber -> robust constant).

This script measures exactly (a) and (b), and answers a more upstream question:
**in the regime where the flow gap is almost entirely flattened by clip (step 2 measured 100% saturation of non-degenerate rollouts at β=8),
does the choice of constant still matter?**

The rewards use the **real groups** from `p6/passk`; the `log π_ref − log π_old` term **is synthetic**
(unavailable before a forward pass), generated as per-token drift × |y|, with a sweepable magnitude.
After a forward pass, this script should be rerun with the true values.

Usage: python3 tools/p7/p7_estimators.py
"""
import json, os, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(REPO, "tools"))
from parse_dump import TURN_SPLIT                      # noqa: E402

EPS_LOW, EPS_HIGH = 0.2, 0.28                          # paper Table 9
RNG = np.random.default_rng(20260901)


# ---------- three constants ----------
def c_mean(T):
    """GFlowRL Eq. 4: arithmetic mean (= the optimal constant under square loss)."""
    return T.mean(axis=-1)


def c_median(T):
    """One instance of DevGrad: when f makes the loss the absolute value, the optimal constant is the median."""
    return np.median(T, axis=-1)


def c_huber(T, delta=EPS_HIGH):
    """Another instance of DevGrad: the optimal constant for Huber loss (solved by IRLS, delta set to the clip width)."""
    c = np.median(T, axis=-1)
    for _ in range(60):
        rres = T - c[..., None]
        w = np.where(np.abs(rres) <= delta, 1.0, delta / np.maximum(np.abs(rres), 1e-12))
        c = (w * T).sum(-1) / np.maximum(w.sum(-1), 1e-12)
    return c


EST = {"mean(GFlowRL)": c_mean, "median(DevGrad|·|)": c_median, "huber(DevGrad)": c_huber}


# ---------- real data ----------
def load_groups(key):
    """Returns (reward matrix [n,G], assistant character-length matrix [n,G]). Length is a proxy for tokens."""
    path = os.path.join(REPO, "01_official_checkpoint_eval", "p6", "passk", key, "0.jsonl")
    g = {}
    for line in open(path):
        d = json.loads(line)
        g.setdefault(d["index"], []).append(d)
    R, L = [], []
    for v in g.values():
        R.append([x["score"] for x in v])
        L.append([_alen(x["output"]) for x in v])
    return np.array(R, float), np.array(L, float)


def _alen(output):
    """Number of characters generated by the assistant; the split follows parse_dump's convention (see step 2)."""
    chunks = TURN_SPLIT.split(output)
    lead = not output.lstrip().startswith("<|im_start|>")
    n = 0
    for i, ch in enumerate(chunks):
        if not ch.strip():
            continue
        if i == 0 and lead:
            role, body = "assistant", ch
        else:
            head, _, body = ch.partition("\n")
            role = head.strip().replace("<|im_end|>", "").strip()
        if role == "assistant":
            n += len(body.replace("<|im_end|>", ""))
    return max(n, 1)


def main():
    print("# P7 criterion i-b · three within-batch constants (synthetic drift, real rewards)\n")
    print("Rewards: real G=5 groups from p6/passk   drift term log π_ref − log π_old: synthetic, sweepable magnitude")
    print("Length |y|: assistant character count (token proxy)\n")

    for key in ("robospatial", "boppose"):
        R, L = load_groups(key)
        n, G = R.shape
        print(f"{'='*78}\n## {key}   prompts={n}  G={G}\n")

        # ---------- (0) starting point: are the three really identical ----------
        T0 = 8.0 * R                                   # drift=0 => T_i = beta*r_i
        cs = {k: f(T0) for k, f in EST.items()}
        d_med = np.abs(cs["mean(GFlowRL)"] - cs["median(DevGrad|·|)"]).mean()
        d_hub = np.abs(cs["mean(GFlowRL)"] - cs["huber(DevGrad)"]).mean()
        print(f"   (0) starting point (π_old=π_ref, drift=0, beta=8): mean absolute difference of the three constants")
        print(f"       mean vs median {d_med:.4f}   mean vs huber {d_hub:.4f}")
        print(f"       -> under square loss, mean and median/huber **already differ** (different f),")
        print(f"          but π_θ=π_old makes GFlowRL and VarGrad numerically coincide.\n")

        # ---------- (1) beta × drift 2-D sweep ----------
        print(f"   (1) saturation rate and sign-disagreement rate: beta × per-token drift sd")
        print(f"       saturation = fraction of |g| outside the clip interval; sign disagreement = fraction where, after clip, the g̃ given by mean and huber")
        print(f"       have different signs (**after saturation only the sign is still alive**)")
        hdr = "       {:>10}".format("drift sd") + "".join(f"{('b=%g'%b_):>18}" for b_ in (0.5, 1.0, 2.0, 8.0))
        print(hdr)
        for sd in (0.0, 0.0003, 0.001, 0.003, 0.01, 0.03):
            drift = RNG.normal(0, sd, size=R.shape) * L if sd > 0 else np.zeros_like(R)
            cells = []
            for beta in (0.5, 1.0, 2.0, 8.0):
                T = beta * R + drift
                g_m = c_mean(T)[:, None] - drift / L - beta * R
                g_h = c_huber(T)[:, None] - drift / L - beta * R
                sat = np.mean((g_m < -EPS_LOW) | (g_m > EPS_HIGH))
                gt_m = np.clip(g_m, -EPS_LOW, EPS_HIGH)
                gt_h = np.clip(g_h, -EPS_LOW, EPS_HIGH)
                dis = np.mean(np.sign(gt_m) != np.sign(gt_h))
                cells.append(f"{100*sat:7.1f}% /{100*dis:6.1f}%")
            print("       {:>10}".format(f"{sd:g}") + "".join(f"{c:>18}" for c in cells))
        print(f"       format: saturation rate / sign-disagreement rate")
        print(f"       >>> two points, both opposite to the guess made before writing the script:")
        print(f"           · **once drift is non-zero, the saturation rate shoots to ~100% regardless of beta** —")
        print(f"             because the drift term in C is not normalized while the subtracted term is normalized (the dimension mismatch of §T6),")
        print(f"             and |y| in the thousands pushes g far beyond the clip interval. beta only decides things in the drift=0 row.")
        print(f"           · **saturation does not mean the choice of constant is irrelevant.** clip cuts the magnitude, what survives is the sign,")
        print(f"             and the sign still depends on C: mean and huber give opposite directions on ~1/5 of rollouts.\n")

        # ---------- (1b) are the g̃ within a group flattened to the same value ----------
        print(f"   (1b) **a sharper question**: are the G values of g̃ within a group flattened to the same value?")
        print(f"        g_i = C − d_i/|y_i| − beta*r_i, while the drift term in C is **not normalized**,")
        print(f"        and the subtracted d_i/|y_i| **is normalized** => within a group the drift is approximately a **common shift**.")
        print(f"        Once the common shift exceeds the clip half-width, the whole group is pushed to the same side, and **the reward's contribution is wiped out completely**.")
        print(f"        {'drift sd':>10} {'median |drift contribution to C|':>20} {'fraction of groups with identical g̃':>20}")
        for sd in (0.0, 0.0003, 0.0005, 0.001, 0.003, 0.01):
            drift = RNG.normal(0, sd, size=R.shape) * L if sd > 0 else np.zeros_like(R)
            T = 8.0 * R + drift
            C = c_mean(T)[:, None]
            g = C - drift / L - 8.0 * R
            gt = np.clip(g, -EPS_LOW, EPS_HIGH)
            uniform = np.mean(np.ptp(gt, axis=1) < 1e-12)
            contrib = np.median(np.abs(drift.mean(axis=1)))
            print(f"        {sd:10g} {contrib:20.4f} {100*uniform:19.1f}%")
        thr = EPS_HIGH * np.sqrt(G) / float(np.median(L))
        print(f"        >>> The threshold can be computed directly: sd of C's drift contribution ≈ per-token drift × |y| / sqrt(G),")
        print(f"            setting it equal to eps_high={EPS_HIGH} gives per-token drift ≈ {thr:.1e} nat.")
        print(f"            **With a clip half-width of {EPS_HIGH} against an unnormalized sum over |y|≈{np.median(L):.0f}, the tolerance is this small.**\n")

        # ---------- (2) sampling variance of the estimators themselves ----------
        print(f"   (2) sampling variance of the estimators (fixed true value, draw G samples 20000 times)")
        print(f"       {'G':>4} {'noise dist':>10} {'Var(mean)':>11} {'Var(median)':>12} {'Var(huber)':>11}  {'relative to mean':>18}")
        for G_ in (5, 16):
            for label, gen in (("Gaussian", lambda s_: RNG.normal(0, 1.0, s_)),
                               ("heavy-tail t3", lambda s_: RNG.standard_t(3, s_)),
                               ("binary+noise", lambda s_: 8.0 * RNG.integers(0, 2, s_) + RNG.normal(0, 1.0, s_))):
                T = gen((20000, G_))
                v = {k: float(np.var(f(T))) for k, f in EST.items()}
                rel = (f"median {v['median(DevGrad|·|)']/v['mean(GFlowRL)']:.2f}x  "
                       f"huber {v['huber(DevGrad)']/v['mean(GFlowRL)']:.2f}x")
                print(f"       {G_:4d} {label:>10} {v['mean(GFlowRL)']:11.4f}"
                      f" {v['median(DevGrad|·|)']:12.4f} {v['huber(DevGrad)']:11.4f}  {rel:>18}")
        print(f"       >>> under Gaussian, mean is best (median about 1.2-1.5x); **under heavy-tail t3, median/huber are clearly more stable**;")
        print(f"           while on a bimodal distribution like **binary reward + noise**, median is actually worse — it chases one of the peaks.")
        print(f"           Which kind our drift term actually is, **only a forward pass can answer**. This is where criterion i-b lands.\n")

        # ---------- (3) sg or not: how much does the constant move once things drift within a minibatch ----------
        print(f"   (3) is sg[] worth it (GFlowRL freezes the constant, VarGrad does not)")
        print(f"       {'per-token drift within minibatch':>26} {'constant shift (mean)':>16} {'relative to beta*r range':>16}")
        T_ref = 8.0 * R + drift
        C_ref = c_mean(T_ref)
        for extra in (0.001, 0.003, 0.01, 0.03):
            d2 = drift + RNG.normal(0, extra, size=R.shape) * L
            C_new = c_mean(8.0 * R + d2)
            move = np.abs(C_new - C_ref).mean()
            print(f"       {extra:26.3f} {move:16.4f} {move/8.0:16.4f}")
        print(f"       >>> the constant's shift is proportional to |y| (the dimension mismatch of §T6),")
        print(f"           so what sg[] freezes can drift within a minibatch by more than the range of beta*r.\n")


        # ---------- (4) candidate fix: apply length normalization to Eq. 4 as well ----------
        print(f"   (4) candidate fix: what if the logprob term in Z_t (Eq. 4) is **also** normalized by |y|?")
        print(f"       C_norm = mean_i[ beta*r_i + (log pi_ref − log pi_old)_i / |y_i| ]")
        print(f"       Then C has the same dimension as the term it centers, and the common shift should disappear.")
        print(f"       {'drift sd':>10} | {'Eq.4 as is':>22} | {'after length normalization':>22}")
        print(f"       {'':>10} | {'saturation':>10}{'group same':>12} | {'saturation':>10}{'group same':>12}")
        for sd in (0.0003, 0.001, 0.003, 0.01, 0.03):
            drift = RNG.normal(0, sd, size=R.shape) * L
            out = []
            for norm in (False, True):
                T = 8.0 * R + (drift / L if norm else drift)
                C = c_mean(T)[:, None]
                g = C - drift / L - 8.0 * R
                gt = np.clip(g, -EPS_LOW, EPS_HIGH)
                sat = np.mean((g < -EPS_LOW) | (g > EPS_HIGH))
                uni = np.mean(np.ptp(gt, axis=1) < 1e-12)
                out.append((sat, uni))
            print(f"       {sd:10g} | {100*out[0][0]:9.1f}%{100*out[0][1]:11.1f}%"
                  f" | {100*out[1][0]:9.1f}%{100*out[1][1]:11.1f}%")
        print(f"       >>> after normalization, the saturation rate and same-value-group rate **return to the drift=0 level and no longer grow with drift**.")
        print(f"           That is, the \"reward contribution wiped out\" mechanism of §1b **comes from the normalization mismatch between Eq.4 and Eq.5")
        print(f"           itself, not from GFlowRL's within-batch estimation idea**.")
        print(f"           ⚠ but this change **changes the fixed point** (Prop. B.1 is proved without normalization),")
        print(f"              cost unknown — this is a candidate to be tested, not a conclusion.\n")


if __name__ == "__main__":
    main()
