#!/usr/bin/env python3
"""P7 step 2 (offline part): on the G=5 groups of p6/passk, decompose the two terms of Z_t that can be decomposed offline.

Z_t(x) = (1/G) Σ_i ( β·r(x,y_i) + log π_ref(y_i|x) − log π_old(y_i|x) )      [Eq. 4]

Of the three terms, β·r is fully offline; the two logprob terms need one forward pass (no tools, no sglang pool),
which this script does not touch. But **length** is available offline, and per Remark B.4, length determines the effective inverse temperature of the fixed point:

    π_θ*(y|x) = π_ref(y|x) · exp( |y| · ( β·r − Z_t(x) ) )        [Remark B.4]

So this script measures three things:
  A. within-group spread of β·r (including the fraction of reward-degenerate groups)
  B. decomposition of |y|: assistant-generated vs <tool_response>.
     Record of decision §5.1 item 2: |y| must be the number of tokens generated by the policy, not the raw response length.
  D. clip saturation fraction of the flow gap (at the training starting point π_old=π_ref, g_i = β·(r̄ − r_i), computable purely offline)
  C. spread of the effective inverse temperature |y|·β derived from B — i.e. how much Remark B.4's premise "lengths vary only
     modestly within rollout groups" is violated on our data.

⚠ The unit is **characters**, not tokens (no tokenizer on this machine; models/ is on the GPU machine).
   Characters are a proxy for tokens: the magnitudes of ratios and spreads are trustworthy, absolute values are not.
   Exact token counts come for free in the forward-pass step; sections B/C of this script should be rerun then.

The split follows the TURN_SPLIT and leading_is_assistant conventions of tools/parse_dump.py —
**do not rewrite the split yourself** (P3 got bitten: a home-built splitter silently dropped the assistant's first turn,
and depth_estimator vanished entirely from the tool histogram of the depth benchmarks).
The script has a built-in regression check: the number of turns must match verl's num_turns.

Usage:  python3 tools/p7/p7_zt_offline.py [--beta 8]
"""
import argparse, json, os, statistics as st, sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(REPO, "tools"))
from parse_dump import TURN_SPLIT, parse_transcript   # noqa: E402

BENCHES = ["robospatial", "blinkdepth", "boppose"]


def split_lengths(output: str):
    """Split per parse_dump's convention, accumulating only character counts.

    Returns (assistant_chars, tool_chars, n_assistant_turns, n_user_turns).
    """
    chunks = TURN_SPLIT.split(output)
    leading_is_assistant = not output.lstrip().startswith("<|im_start|>")
    a_chars = t_chars = 0
    n_a = n_u = 0
    for idx, chunk in enumerate(chunks):
        if not chunk.strip():
            continue
        if idx == 0 and leading_is_assistant:
            role, body = "assistant", chunk
        else:
            head, _, body = chunk.partition("\n")
            role = head.strip().replace("<|im_end|>", "").strip()
        body = body.replace("<|im_end|>", "")
        if role == "assistant":
            a_chars += len(body); n_a += 1
        elif role in ("user", "tool"):
            t_chars += len(body); n_u += 1
    return a_chars, t_chars, n_a, n_u


def rel_range(xs):
    m = st.mean(xs)
    return (max(xs) - min(xs)) / m if m else 0.0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--beta", type=float, default=8.0)
    ap.add_argument("--root", default=os.path.join(REPO, "01_official_checkpoint_eval", "p6", "passk"))
    a = ap.parse_args()
    beta = a.beta

    print(f"# P7 step 2 · the two offline terms of Z_t   beta={beta:g}   length unit=characters (token proxy)\n")

    for key in BENCHES:
        path = os.path.join(a.root, key, "0.jsonl")
        groups = defaultdict(list)
        with open(path) as f:
            for line in f:
                d = json.loads(line)
                groups[d["index"]].append(d)

        sizes = {len(v) for v in groups.values()}
        # ---- regression check: the number of split turns must be consistent with verl's num_turns ----
        bad = 0
        for v in groups.values():
            for d in v:
                _, _, n_a, n_u = split_lengths(d["output"])
                if n_a + n_u + 1 != d["num_turns"]:
                    bad += 1
        tot = sum(len(v) for v in groups.values())

        # ---- A. beta*r ----
        degen = 0
        br_sd_in_group, br_range = [], []
        # ---- B/C. length ----
        a_all, raw_all, ratio_all = [], [], []
        a_relrange, raw_relrange = [], []
        for v in groups.values():
            r = [x["score"] for x in v]
            if max(r) - min(r) < 1e-9:
                degen += 1
            br = [beta * x for x in r]
            br_sd_in_group.append(st.pstdev(br))
            br_range.append(max(br) - min(br))

            ac, rawc = [], []
            for d in v:
                ach, tch, _, _ = split_lengths(d["output"])
                ac.append(max(ach, 1))
                rawc.append(max(ach + tch, 1))
            a_all += ac; raw_all += rawc
            ratio_all += [rr / aa for aa, rr in zip(ac, rawc)]
            a_relrange.append(rel_range(ac))
            raw_relrange.append(rel_range(rawc))

        n = len(groups)
        print(f"## {key}   prompts={n}  group sizes={sorted(sizes)}  rollouts={tot}")
        print(f"   regression check (split turns vs verl num_turns): mismatched {bad}/{tot}"
              f"   {'OK' if bad == 0 else '<<< FAILED, the numbers below are unusable'}")
        print(f"   A. beta*r within-group sd   mean {st.mean(br_sd_in_group):.3f}"
              f"   median {st.median(br_sd_in_group):.3f}"
              f"   mean range {st.mean(br_range):.3f}")
        print(f"      reward-degenerate groups (r identical within G)  {degen}/{n} = {100*degen/n:.1f}%")
        print(f"   B. |y| assistant-generated    mean {st.mean(a_all):8.0f}"
              f"   median {st.median(a_all):8.0f}   min {min(a_all)}  max {max(a_all)}")
        print(f"      |y| raw response           mean {st.mean(raw_all):8.0f}"
              f"   median {st.median(raw_all):8.0f}   min {min(raw_all)}  max {max(raw_all)}")
        print(f"      raw/assistant multiple     median {st.median(ratio_all):.2f}×"
              f"   mean {st.mean(ratio_all):.2f}×   max {max(ratio_all):.2f}×")
        print(f"   C. within-group relative range of |y| (max-min)/mean")
        print(f"      using assistant length       mean {st.mean(a_relrange):.2f}"
              f"   median {st.median(a_relrange):.2f}   max {max(a_relrange):.2f}")
        print(f"      using raw response length    mean {st.mean(raw_relrange):.2f}"
              f"   median {st.median(raw_relrange):.2f}   max {max(raw_relrange):.2f}")
        print(f"      cross-prompt |y| range ratio  max/min = {max(a_all)/min(a_all):.1f}×")

        # ---- D. clip saturation ----
        EPS_LOW, EPS_HIGH = 0.2, 0.28          # paper Table 9
        sat = tot_r = sat_nd = tot_nd = 0
        for v in groups.values():
            rr = [x["score"] for x in v]
            rbar = st.mean(rr)
            deg = (max(rr) - min(rr)) < 1e-9
            for x in rr:
                g = beta * (rbar - x)
                hit = (g < -EPS_LOW) or (g > EPS_HIGH)
                sat += hit; tot_r += 1
                if not deg:
                    sat_nd += hit; tot_nd += 1
        print(f"   D. fraction of flow gap cut by clip at the starting point (g_i = beta*(r_bar - r_i))")
        print(f"      all rollouts               {sat}/{tot_r} = {100*sat/tot_r:.1f}%")
        if tot_nd:
            print(f"      non-degenerate groups only {sat_nd}/{tot_nd} = {100*sat_nd/tot_nd:.1f}%"
                  f"   <- g of degenerate groups is identically 0, they should not be counted in the first place")
        print()


if __name__ == "__main__":
    main()
